### ISSUE TITLE
Cleaner Imports

### ISSUE THREAD

**Issue by aspidites** [tel/serv#9]
At the moment, there is a lot of ceremony required to get up and running with Serv. If you compare the minimal imports for Servant and Serv, you'll see:

Two in Servant:
```haskell
import Servant
import Servant.Server
```

Versus 6 in Serv:
```haskell
import Serv.Api
import Serv.Common
import qualified Serv.ContentType as Ct
import Serv.Header as H
import Serv.StatusCode as Sc
import Serv.Server

**Comment by tel** [comment]
First, this is really important so thanks for bringing it up. I think it is absolutely important to have a good import story for Serv. "Good" here means (1) minimal, (2) traceable so that users can tell where things are being imported from, and (3) respecting of an eventual `servant`-like divide between the `Api` core, the server, the client, the swagger docs, etc.

Second, the thing that's most crucial here in causing the explosion is the separation of the headers, content types, and status codes into separate modules. This is largely in order to allow the API types to be imported without qualification (since `Api.:>` is really ugly) but without cluttering the global namespace with the very large status code and header import lists.

I'd be interested to consider a `Serv.Server.Simple` import (perhaps that's poorly named?) which imports everything you might need all at once.

**Comment by aspidites** [comment]
That could work. What if you called it a prelude? In my head, if i see "Prelude", I know I'm importing the most commonly used things, and as such, might be importing other stuff that I don't really need.

**Comment by tel** [comment]
That's a good idea—vastly better than `Simple`!

**Comment by tel** [comment]
So thinking about this I think what needs to happen are use-case oriented imports. Ignoring all `Internal` modules for the moment, I propose something that looks a bit like this:

- `Serv.Api.Prelude` provides everything you need in order to define an `Api` type
- `Serv.Server.Prelude` does about the same for constructing `Server`s
- `Serv.*.Prelude` handles this for other future `Serv` extensions (client, swagger, etc)

This makes me feel that `Serv.Api` and `Serv.Server` should be deprecated since with the `Prelude` modules in place those namespaces seem too "high" up the hierarchy for the rather more specific exports that they offer. We could replace them with `Serv.Api.Core` and `Serv.Api.Server`, perhaps?

**Comment by tel** [comment]
The new module design has two modules, `Serv.Api.Prelude` and `Serv.Wai.Prelude` which offer this sort of functionality. Right now they're both a little... aggressive and just dump most of the interesting symbols into the namespace without thought, but it's a start.

**Comment by tel** [comment]
There should be some testing to ensure that these genuinely are all that are needed for constructing `Api` types and `Server`s. Offhand I already know that `Serv.Wai.Prelude` is insufficient since it doesn't export the `Response` building machinery or anything to do with `Rec`s.

**Comment by tel** [comment]
I think this is resolved now! See the improvement in [`Examples.Ex1`](https://github.com/tel/serv/blob/master/serv-wai/test/Examples/Ex1.hs).

**Comment by aspidites** [comment]
:+1: Much cleaner, and gives me a path to do more fine grained stuff if I prefer that to the concise imports. Thanks a lot.
